<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: master
 * Date: Thu, 21 Nov 2024 06:48:26 +0100
 */

$conf['title'] = 'AB-S';
$conf['license'] = 'publicdomain';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['latex']['latex_path'] = 'C:/texlive/2024/bin/windows/latex';
$conf['plugin']['latex']['dvips_path'] = 'C:/texlive/2024/bin/windows/dvips';
$conf['plugin']['latex']['identify_path'] = 'C:/texlive/2024/bin/windows/identify';
$conf['plugin']['latex']['convert_path'] = 'C:/texlive/2024/bin/windows/convert';

// end auto-generated content
